import type { ColourPreset } from '@/types'

export const colourPresets: ColourPreset[] = [
  // Colour Adjectives (50)
  {
    id: 'passionate',
    label: 'Passionate',
    labelJa: '情熱的',
    tailwind: { color: 'red', shade: 500 },
    searchTerms: ['passion', 'love', 'energy'],
    isOnomatopoeia: false,
  },
  {
    id: 'bold-red',
    label: 'Bold',
    labelJa: '大胆な',
    tailwind: { color: 'red', shade: 600 },
    searchTerms: ['bold', 'strong', 'powerful'],
    isOnomatopoeia: false,
  },
  {
    id: 'soft-red',
    label: 'Soft Red',
    labelJa: '柔らかい赤',
    tailwind: { color: 'red', shade: 300 },
    searchTerms: ['soft', 'gentle', 'warm'],
    isOnomatopoeia: false,
  },
  {
    id: 'energetic',
    label: 'Energetic',
    labelJa: 'エネルギッシュ',
    tailwind: { color: 'orange', shade: 500 },
    searchTerms: ['energy', 'vibrant', 'active'],
    isOnomatopoeia: false,
  },
  {
    id: 'warm',
    label: 'Warm',
    labelJa: '暖かい',
    tailwind: { color: 'orange', shade: 400 },
    searchTerms: ['warm', 'cozy', 'friendly'],
    isOnomatopoeia: false,
  },
  {
    id: 'sunset',
    label: 'Sunset',
    labelJa: '夕焼け',
    tailwind: { color: 'orange', shade: 600 },
    searchTerms: ['sunset', 'dusk', 'evening'],
    isOnomatopoeia: false,
  },
  {
    id: 'golden',
    label: 'Golden',
    labelJa: 'ゴールデン',
    tailwind: { color: 'amber', shade: 400 },
    searchTerms: ['gold', 'luxury', 'premium'],
    isOnomatopoeia: false,
  },
  {
    id: 'harvest',
    label: 'Harvest',
    labelJa: '収穫',
    tailwind: { color: 'amber', shade: 500 },
    searchTerms: ['autumn', 'harvest', 'natural'],
    isOnomatopoeia: false,
  },
  {
    id: 'honey',
    label: 'Honey',
    labelJa: 'ハニー',
    tailwind: { color: 'amber', shade: 300 },
    searchTerms: ['honey', 'sweet', 'warm'],
    isOnomatopoeia: false,
  },
  {
    id: 'cheerful',
    label: 'Cheerful',
    labelJa: '陽気な',
    tailwind: { color: 'yellow', shade: 400 },
    searchTerms: ['happy', 'cheerful', 'bright'],
    isOnomatopoeia: false,
  },
  {
    id: 'optimistic',
    label: 'Optimistic',
    labelJa: '楽観的',
    tailwind: { color: 'yellow', shade: 500 },
    searchTerms: ['optimism', 'positive', 'sunny'],
    isOnomatopoeia: false,
  },
  {
    id: 'pale-yellow',
    label: 'Pale',
    labelJa: '淡い黄色',
    tailwind: { color: 'yellow', shade: 200 },
    searchTerms: ['soft', 'light', 'gentle'],
    isOnomatopoeia: false,
  },
  {
    id: 'fresh',
    label: 'Fresh',
    labelJa: 'フレッシュ',
    tailwind: { color: 'lime', shade: 400 },
    searchTerms: ['fresh', 'new', 'spring'],
    isOnomatopoeia: false,
  },
  {
    id: 'vibrant',
    label: 'Vibrant',
    labelJa: '鮮やか',
    tailwind: { color: 'lime', shade: 500 },
    searchTerms: ['vibrant', 'lively', 'dynamic'],
    isOnomatopoeia: false,
  },
  {
    id: 'natural',
    label: 'Natural',
    labelJa: 'ナチュラル',
    tailwind: { color: 'green', shade: 500 },
    searchTerms: ['nature', 'organic', 'eco'],
    isOnomatopoeia: false,
  },
  {
    id: 'growth',
    label: 'Growth',
    labelJa: '成長',
    tailwind: { color: 'green', shade: 600 },
    searchTerms: ['growth', 'success', 'progress'],
    isOnomatopoeia: false,
  },
  {
    id: 'calm-green',
    label: 'Calm Green',
    labelJa: '穏やかな緑',
    tailwind: { color: 'green', shade: 300 },
    searchTerms: ['calm', 'peaceful', 'serene'],
    isOnomatopoeia: false,
  },
  {
    id: 'luxurious',
    label: 'Luxurious',
    labelJa: '高級な',
    tailwind: { color: 'emerald', shade: 500 },
    searchTerms: ['luxury', 'premium', 'elegant'],
    isOnomatopoeia: false,
  },
  {
    id: 'sophisticated',
    label: 'Sophisticated',
    labelJa: '洗練された',
    tailwind: { color: 'emerald', shade: 600 },
    searchTerms: ['sophisticated', 'refined'],
    isOnomatopoeia: false,
  },
  {
    id: 'balanced',
    label: 'Balanced',
    labelJa: 'バランス',
    tailwind: { color: 'teal', shade: 500 },
    searchTerms: ['balance', 'harmony', 'stable'],
    isOnomatopoeia: false,
  },
  {
    id: 'professional',
    label: 'Professional',
    labelJa: 'プロフェッショナル',
    tailwind: { color: 'teal', shade: 600 },
    searchTerms: ['professional', 'corporate'],
    isOnomatopoeia: false,
  },
  {
    id: 'refreshing',
    label: 'Refreshing',
    labelJa: '爽やか',
    tailwind: { color: 'cyan', shade: 400 },
    searchTerms: ['refresh', 'clean', 'crisp'],
    isOnomatopoeia: false,
  },
  {
    id: 'digital',
    label: 'Digital',
    labelJa: 'デジタル',
    tailwind: { color: 'cyan', shade: 500 },
    searchTerms: ['digital', 'tech', 'modern'],
    isOnomatopoeia: false,
  },
  {
    id: 'open',
    label: 'Open',
    labelJa: '開放的',
    tailwind: { color: 'sky', shade: 400 },
    searchTerms: ['open', 'free', 'spacious'],
    isOnomatopoeia: false,
  },
  {
    id: 'trustworthy',
    label: 'Trustworthy',
    labelJa: '信頼できる',
    tailwind: { color: 'sky', shade: 500 },
    searchTerms: ['trust', 'reliable', 'honest'],
    isOnomatopoeia: false,
  },
  {
    id: 'light-sky',
    label: 'Light Sky',
    labelJa: '明るい空',
    tailwind: { color: 'sky', shade: 300 },
    searchTerms: ['light', 'airy', 'soft'],
    isOnomatopoeia: false,
  },
  {
    id: 'confident',
    label: 'Confident',
    labelJa: '自信',
    tailwind: { color: 'blue', shade: 500 },
    searchTerms: ['confidence', 'strong', 'stable'],
    isOnomatopoeia: false,
  },
  {
    id: 'corporate',
    label: 'Corporate',
    labelJa: '企業的',
    tailwind: { color: 'blue', shade: 600 },
    searchTerms: ['corporate', 'business', 'formal'],
    isOnomatopoeia: false,
  },
  {
    id: 'serene',
    label: 'Serene',
    labelJa: '穏やかな青',
    tailwind: { color: 'blue', shade: 400 },
    searchTerms: ['serene', 'calm', 'peaceful'],
    isOnomatopoeia: false,
  },
  {
    id: 'deep-blue',
    label: 'Deep',
    labelJa: '深い青',
    tailwind: { color: 'blue', shade: 700 },
    searchTerms: ['deep', 'serious', 'authority'],
    isOnomatopoeia: false,
  },
  {
    id: 'creative',
    label: 'Creative',
    labelJa: 'クリエイティブ',
    tailwind: { color: 'indigo', shade: 500 },
    searchTerms: ['creative', 'artistic', 'unique'],
    isOnomatopoeia: false,
  },
  {
    id: 'mysterious',
    label: 'Mysterious',
    labelJa: '神秘的',
    tailwind: { color: 'indigo', shade: 600 },
    searchTerms: ['mystery', 'depth', 'intrigue'],
    isOnomatopoeia: false,
  },
  {
    id: 'imaginative',
    label: 'Imaginative',
    labelJa: '想像力豊か',
    tailwind: { color: 'violet', shade: 500 },
    searchTerms: ['imagination', 'dream', 'fantasy'],
    isOnomatopoeia: false,
  },
  {
    id: 'playful-violet',
    label: 'Playful',
    labelJa: '遊び心のある紫',
    tailwind: { color: 'violet', shade: 400 },
    searchTerms: ['playful', 'fun', 'whimsical'],
    isOnomatopoeia: false,
  },
  {
    id: 'royal',
    label: 'Royal',
    labelJa: '高貴な',
    tailwind: { color: 'purple', shade: 600 },
    searchTerms: ['royal', 'noble', 'premium'],
    isOnomatopoeia: false,
  },
  {
    id: 'elegant',
    label: 'Elegant',
    labelJa: 'エレガント',
    tailwind: { color: 'purple', shade: 500 },
    searchTerms: ['elegant', 'graceful', 'refined'],
    isOnomatopoeia: false,
  },
  {
    id: 'bold-pink',
    label: 'Bold Pink',
    labelJa: '大胆なピンク',
    tailwind: { color: 'fuchsia', shade: 500 },
    searchTerms: ['bold', 'striking', 'vibrant'],
    isOnomatopoeia: false,
  },
  {
    id: 'expressive',
    label: 'Expressive',
    labelJa: '表現豊か',
    tailwind: { color: 'fuchsia', shade: 400 },
    searchTerms: ['expressive', 'artistic'],
    isOnomatopoeia: false,
  },
  {
    id: 'romantic',
    label: 'Romantic',
    labelJa: 'ロマンチック',
    tailwind: { color: 'pink', shade: 400 },
    searchTerms: ['romantic', 'love', 'gentle'],
    isOnomatopoeia: false,
  },
  {
    id: 'friendly',
    label: 'Friendly',
    labelJa: 'フレンドリー',
    tailwind: { color: 'pink', shade: 300 },
    searchTerms: ['friendly', 'approachable'],
    isOnomatopoeia: false,
  },
  {
    id: 'feminine',
    label: 'Feminine',
    labelJa: 'フェミニン',
    tailwind: { color: 'rose', shade: 400 },
    searchTerms: ['feminine', 'soft', 'delicate'],
    isOnomatopoeia: false,
  },
  {
    id: 'tender',
    label: 'Tender',
    labelJa: '優しい',
    tailwind: { color: 'rose', shade: 300 },
    searchTerms: ['tender', 'gentle', 'caring'],
    isOnomatopoeia: false,
  },
  {
    id: 'modern',
    label: 'Modern',
    labelJa: 'モダン',
    tailwind: { color: 'slate', shade: 500 },
    searchTerms: ['modern', 'sleek', 'contemporary'],
    isOnomatopoeia: false,
  },
  {
    id: 'neutral-cool',
    label: 'Neutral Cool',
    labelJa: 'クールな中性色',
    tailwind: { color: 'slate', shade: 400 },
    searchTerms: ['neutral', 'cool', 'balanced'],
    isOnomatopoeia: false,
  },
  {
    id: 'minimal',
    label: 'Minimal',
    labelJa: 'ミニマル',
    tailwind: { color: 'gray', shade: 500 },
    searchTerms: ['minimal', 'simple', 'clean'],
    isOnomatopoeia: false,
  },
  {
    id: 'understated',
    label: 'Understated',
    labelJa: '控えめ',
    tailwind: { color: 'gray', shade: 400 },
    searchTerms: ['understated', 'subtle'],
    isOnomatopoeia: false,
  },
  {
    id: 'industrial',
    label: 'Industrial',
    labelJa: 'インダストリアル',
    tailwind: { color: 'zinc', shade: 600 },
    searchTerms: ['industrial', 'urban', 'raw'],
    isOnomatopoeia: false,
  },
  {
    id: 'tech',
    label: 'Tech',
    labelJa: 'テック',
    tailwind: { color: 'zinc', shade: 500 },
    searchTerms: ['tech', 'digital', 'modern'],
    isOnomatopoeia: false,
  },
  {
    id: 'clean',
    label: 'Clean',
    labelJa: 'クリーン',
    tailwind: { color: 'neutral', shade: 100 },
    searchTerms: ['clean', 'pure', 'simple'],
    isOnomatopoeia: false,
  },
  {
    id: 'timeless',
    label: 'Timeless',
    labelJa: '時代を超えた',
    tailwind: { color: 'neutral', shade: 500 },
    searchTerms: ['timeless', 'classic'],
    isOnomatopoeia: false,
  },
  {
    id: 'earthy',
    label: 'Earthy',
    labelJa: 'アーシー',
    tailwind: { color: 'stone', shade: 500 },
    searchTerms: ['earth', 'natural', 'organic'],
    isOnomatopoeia: false,
  },
  {
    id: 'grounded',
    label: 'Grounded',
    labelJa: '地に足のついた',
    tailwind: { color: 'stone', shade: 600 },
    searchTerms: ['grounded', 'stable', 'solid'],
    isOnomatopoeia: false,
  },

  // Colour Onomatopoeia (30)
  {
    id: 'wakuwaku-colour',
    label: 'Exciting',
    labelJa: 'わくわく',
    tailwind: { color: 'orange', shade: 400 },
    searchTerms: ['exciting', 'anticipation', 'vibrant'],
    isOnomatopoeia: true,
  },
  {
    id: 'dokidoki-colour',
    label: 'Thrilling',
    labelJa: 'どきどき',
    tailwind: { color: 'rose', shade: 500 },
    searchTerms: ['heartbeat', 'thrill', 'romance'],
    isOnomatopoeia: true,
  },
  {
    id: 'ukiuki-colour',
    label: 'Uplifting',
    labelJa: 'うきうき',
    tailwind: { color: 'yellow', shade: 400 },
    searchTerms: ['cheerful', 'light', 'happy'],
    isOnomatopoeia: true,
  },
  {
    id: 'kyunkyun-colour',
    label: 'Heartwarming',
    labelJa: 'きゅんきゅん',
    tailwind: { color: 'pink', shade: 400 },
    searchTerms: ['sweet', 'cute', 'romantic'],
    isOnomatopoeia: true,
  },
  {
    id: 'runrun-colour',
    label: 'Joyful',
    labelJa: 'るんるん',
    tailwind: { color: 'lime', shade: 400 },
    searchTerms: ['joyful', 'bouncy', 'fresh'],
    isOnomatopoeia: true,
  },
  {
    id: 'kirakira-colour',
    label: 'Sparkling',
    labelJa: 'きらきら',
    tailwind: { color: 'amber', shade: 300 },
    searchTerms: ['sparkle', 'glitter', 'shine'],
    isOnomatopoeia: true,
  },
  {
    id: 'pikapika-colour',
    label: 'Shiny',
    labelJa: 'ぴかぴか',
    tailwind: { color: 'yellow', shade: 300 },
    searchTerms: ['shiny', 'polished', 'bright'],
    isOnomatopoeia: true,
  },
  {
    id: 'tsuyatsuya-colour',
    label: 'Glossy',
    labelJa: 'つやつや',
    tailwind: { color: 'fuchsia', shade: 300 },
    searchTerms: ['glossy', 'lustrous', 'sleek'],
    isOnomatopoeia: true,
  },
  {
    id: 'kirari-colour',
    label: 'Gleaming',
    labelJa: 'きらり',
    tailwind: { color: 'amber', shade: 400 },
    searchTerms: ['gleam', 'flash', 'moment'],
    isOnomatopoeia: true,
  },
  {
    id: 'giragira-colour',
    label: 'Glaring',
    labelJa: 'ぎらぎら',
    tailwind: { color: 'orange', shade: 600 },
    searchTerms: ['glare', 'intense', 'strong'],
    isOnomatopoeia: true,
  },
  {
    id: 'fuwafuwa-colour',
    label: 'Fluffy',
    labelJa: 'ふわふわ',
    tailwind: { color: 'sky', shade: 200 },
    searchTerms: ['fluffy', 'light', 'airy'],
    isOnomatopoeia: true,
  },
  {
    id: 'funwari-colour',
    label: 'Soft',
    labelJa: 'ふんわり',
    tailwind: { color: 'pink', shade: 200 },
    searchTerms: ['soft', 'gentle', 'delicate'],
    isOnomatopoeia: true,
  },
  {
    id: 'mofumofu-colour',
    label: 'Cozy',
    labelJa: 'もふもふ',
    tailwind: { color: 'stone', shade: 300 },
    searchTerms: ['cozy', 'warm', 'soft'],
    isOnomatopoeia: true,
  },
  {
    id: 'howahowa-colour',
    label: 'Gentle',
    labelJa: 'ほわほわ',
    tailwind: { color: 'rose', shade: 200 },
    searchTerms: ['warm', 'fuzzy', 'gentle'],
    isOnomatopoeia: true,
  },
  {
    id: 'yuruyuru-colour',
    label: 'Loose',
    labelJa: 'ゆるゆる',
    tailwind: { color: 'teal', shade: 200 },
    searchTerms: ['relaxed', 'loose', 'easy'],
    isOnomatopoeia: true,
  },
  {
    id: 'sukkiri-colour',
    label: 'Refreshing',
    labelJa: 'すっきり',
    tailwind: { color: 'cyan', shade: 400 },
    searchTerms: ['refresh', 'clear', 'clean'],
    isOnomatopoeia: true,
  },
  {
    id: 'sappari-colour',
    label: 'Crisp',
    labelJa: 'さっぱり',
    tailwind: { color: 'sky', shade: 400 },
    searchTerms: ['crisp', 'fresh', 'clean'],
    isOnomatopoeia: true,
  },
  {
    id: 'shakitto-colour',
    label: 'Alert',
    labelJa: 'しゃきっと',
    tailwind: { color: 'emerald', shade: 500 },
    searchTerms: ['crisp', 'sharp', 'alert'],
    isOnomatopoeia: true,
  },
  {
    id: 'pakitto-colour',
    label: 'Sharp',
    labelJa: 'ぱきっと',
    tailwind: { color: 'blue', shade: 500 },
    searchTerms: ['clear', 'defined', 'sharp'],
    isOnomatopoeia: true,
  },
  {
    id: 'kiritto-colour',
    label: 'Dignified',
    labelJa: 'きりっと',
    tailwind: { color: 'slate', shade: 600 },
    searchTerms: ['sharp', 'dignified', 'cool'],
    isOnomatopoeia: true,
  },
  {
    id: 'shittori-colour',
    label: 'Subdued',
    labelJa: 'しっとり',
    tailwind: { color: 'indigo', shade: 400 },
    searchTerms: ['moist', 'subdued', 'calm'],
    isOnomatopoeia: true,
  },
  {
    id: 'hokkori-colour',
    label: 'Comforting',
    labelJa: 'ほっこり',
    tailwind: { color: 'orange', shade: 300 },
    searchTerms: ['warm', 'cozy', 'comfort'],
    isOnomatopoeia: true,
  },
  {
    id: 'pokapoka-colour',
    label: 'Warm',
    labelJa: 'ぽかぽか',
    tailwind: { color: 'amber', shade: 400 },
    searchTerms: ['warm', 'sunny', 'gentle'],
    isOnomatopoeia: true,
  },
  {
    id: 'jinwari-colour',
    label: 'Gradual',
    labelJa: 'じんわり',
    tailwind: { color: 'rose', shade: 400 },
    searchTerms: ['gradual', 'spreading', 'warm'],
    isOnomatopoeia: true,
  },
  {
    id: 'mattari-colour',
    label: 'Mellow',
    labelJa: 'まったり',
    tailwind: { color: 'stone', shade: 400 },
    searchTerms: ['mellow', 'relaxed', 'easy'],
    isOnomatopoeia: true,
  },
  {
    id: 'dosshiri-colour',
    label: 'Solid',
    labelJa: 'どっしり',
    tailwind: { color: 'slate', shade: 700 },
    searchTerms: ['solid', 'heavy', 'stable'],
    isOnomatopoeia: true,
  },
  {
    id: 'gacchiri-colour',
    label: 'Robust',
    labelJa: 'がっちり',
    tailwind: { color: 'zinc', shade: 700 },
    searchTerms: ['firm', 'strong', 'solid'],
    isOnomatopoeia: true,
  },
  {
    id: 'zusshiri-colour',
    label: 'Weighty',
    labelJa: 'ずっしり',
    tailwind: { color: 'stone', shade: 700 },
    searchTerms: ['heavy', 'weighty', 'dense'],
    isOnomatopoeia: true,
  },
  {
    id: 'shikkari-colour',
    label: 'Firm',
    labelJa: 'しっかり',
    tailwind: { color: 'blue', shade: 700 },
    searchTerms: ['firm', 'reliable', 'solid'],
    isOnomatopoeia: true,
  },
  {
    id: 'gutto-colour',
    label: 'Impactful',
    labelJa: 'ぐっと',
    tailwind: { color: 'red', shade: 600 },
    searchTerms: ['impact', 'pull', 'strong'],
    isOnomatopoeia: true,
  },
]
