import type { MovementPreset } from '@/types'

export const movementPresets: MovementPreset[] = [
  {
    id: 'none',
    label: 'None',
    labelJa: 'なし',
    description: 'No animation, static',
    descriptionJa: '動きなし、静的',
    cssValue: { animation: 'none' },
  },
  {
    id: 'fade',
    label: 'Fade',
    labelJa: 'フェード',
    description: 'Fade in/out smoothly',
    descriptionJa: 'ふわっと現れる/消える',
    cssValue: { animation: 'subtle' },
  },
  {
    id: 'slide-slow',
    label: 'Slide Slow',
    labelJa: 'ゆっくりスライド',
    description: 'Slide horizontally/vertically slowly',
    descriptionJa: 'ゆったりと横/縦に移動',
    cssValue: { animation: 'subtle' },
  },
  {
    id: 'slide-fast',
    label: 'Slide Fast',
    labelJa: '素早くスライド',
    description: 'Sharp, quick movement',
    descriptionJa: 'シャープに移動',
    cssValue: { animation: 'moderate' },
  },
  {
    id: 'bounce',
    label: 'Bounce',
    labelJa: 'バウンス',
    description: 'Bouncy, spring-like motion',
    descriptionJa: '弾むような動き',
    cssValue: { animation: 'expressive' },
  },
  {
    id: 'pop',
    label: 'Pop',
    labelJa: 'ポップ',
    description: 'Pop in/out quickly',
    descriptionJa: 'パッと飛び出す',
    cssValue: { animation: 'expressive' },
  },
  {
    id: 'float',
    label: 'Float',
    labelJa: 'フロート',
    description: 'Gentle floating motion',
    descriptionJa: 'ふわふわ浮遊する',
    cssValue: { animation: 'subtle' },
  },
  {
    id: 'pulse',
    label: 'Pulse',
    labelJa: 'パルス',
    description: 'Pulsing scale animation',
    descriptionJa: '脈打つように拡縮',
    cssValue: { animation: 'moderate' },
  },
  {
    id: 'shake',
    label: 'Shake',
    labelJa: 'シェイク',
    description: 'Small shaking motion',
    descriptionJa: '小刻みに揺れる',
    cssValue: { animation: 'expressive' },
  },
  {
    id: 'zoom',
    label: 'Zoom',
    labelJa: 'ズーム',
    description: 'Zoom in/out effect',
    descriptionJa: '拡大/縮小して現れる',
    cssValue: { animation: 'moderate' },
  },
]
