import type { SpacePreset } from '@/types'

export const spacePresets: SpacePreset[] = [
  {
    id: 'compact',
    label: 'Compact',
    labelJa: 'コンパクト',
    description: 'Dense, high information density',
    descriptionJa: '詰まった、情報密度高い',
    cssValue: { spacing: 'compact' },
  },
  {
    id: 'dense',
    label: 'Dense',
    labelJa: 'デンス',
    description: 'High density, elements close together',
    descriptionJa: '高密度、要素が近い',
    cssValue: { spacing: 'compact' },
  },
  {
    id: 'normal',
    label: 'Normal',
    labelJa: 'ノーマル',
    description: 'Standard spacing',
    descriptionJa: '標準的な余白',
    cssValue: { spacing: 'normal' },
  },
  {
    id: 'balanced',
    label: 'Balanced',
    labelJa: 'バランス',
    description: 'Well-balanced layout',
    descriptionJa: '整った配置',
    cssValue: { spacing: 'normal' },
  },
  {
    id: 'comfortable',
    label: 'Comfortable',
    labelJa: '快適',
    description: 'Comfortable amount of whitespace',
    descriptionJa: 'ゆとりのある余白',
    cssValue: { spacing: 'normal' },
  },
  {
    id: 'spacious',
    label: 'Spacious',
    labelJa: 'スペーシャス',
    description: 'Lots of whitespace',
    descriptionJa: '広々とした余白',
    cssValue: { spacing: 'spacious' },
  },
  {
    id: 'breathing',
    label: 'Breathing',
    labelJa: 'ブリージング',
    description: 'Breathing room with whitespace',
    descriptionJa: '余白で呼吸感',
    cssValue: { spacing: 'spacious' },
  },
  {
    id: 'airy',
    label: 'Airy',
    labelJa: 'エアリー',
    description: 'Light, airy layout',
    descriptionJa: '空気感のある配置',
    cssValue: { spacing: 'spacious' },
  },
  {
    id: 'generous',
    label: 'Generous',
    labelJa: 'ジェネラス',
    description: 'Generous whitespace',
    descriptionJa: '贅沢な余白',
    cssValue: { spacing: 'spacious' },
  },
  {
    id: 'tight',
    label: 'Tight',
    labelJa: 'タイト',
    description: 'Tight, compact layout',
    descriptionJa: '引き締まった配置',
    cssValue: { spacing: 'compact' },
  },
]
