import type { ColourPreset } from '../../types'

// Vivid Palette (24 colors)
export const vividColours: ColourPreset[] = [
  // Warm
  {
    id: 'red',
    name: 'Red',
    nameJa: '赤',
    hex: '#EF4444',
    description: '情熱・エネルギー・緊急性',
    paletteType: 'vivid',
  },
  {
    id: 'rose',
    name: 'Rose',
    nameJa: 'ローズ',
    hex: '#F43F5E',
    description: '情熱・愛・温かみ',
    paletteType: 'vivid',
  },
  {
    id: 'coral',
    name: 'Coral',
    nameJa: 'コーラル',
    hex: '#FF6B6B',
    description: '親しみ・活発・元気',
    paletteType: 'vivid',
  },
  {
    id: 'orange',
    name: 'Orange',
    nameJa: 'オレンジ',
    hex: '#F97316',
    description: '活力・創造性・親しみ',
    paletteType: 'vivid',
  },
  {
    id: 'amber',
    name: 'Amber',
    nameJa: 'アンバー',
    hex: '#F59E0B',
    description: '温かみ・収穫・注意',
    paletteType: 'vivid',
  },
  {
    id: 'yellow',
    name: 'Yellow',
    nameJa: '黄',
    hex: '#EAB308',
    description: '楽観・明るさ・希望',
    paletteType: 'vivid',
  },
  {
    id: 'gold',
    name: 'Gold',
    nameJa: 'ゴールド',
    hex: '#CA8A04',
    description: '高級・成功・豊かさ',
    paletteType: 'vivid',
  },
  // Green
  {
    id: 'lime',
    name: 'Lime',
    nameJa: 'ライム',
    hex: '#84CC16',
    description: '新鮮・成長・活発',
    paletteType: 'vivid',
  },
  {
    id: 'green',
    name: 'Green',
    nameJa: '緑',
    hex: '#22C55E',
    description: '自然・安心・成長',
    paletteType: 'vivid',
  },
  {
    id: 'emerald',
    name: 'Emerald',
    nameJa: 'エメラルド',
    hex: '#10B981',
    description: '高貴・繁栄・調和',
    paletteType: 'vivid',
  },
  {
    id: 'mint',
    name: 'Mint',
    nameJa: 'ミント',
    hex: '#34D399',
    description: '爽やか・清潔・癒し',
    paletteType: 'vivid',
  },
  {
    id: 'teal',
    name: 'Teal',
    nameJa: 'ティール',
    hex: '#14B8A6',
    description: 'バランス・洗練・信頼',
    paletteType: 'vivid',
  },
  {
    id: 'olive',
    name: 'Olive',
    nameJa: 'オリーブ',
    hex: '#84CC16',
    description: '平和・自然・落ち着き',
    paletteType: 'vivid',
  },
  // Blue
  {
    id: 'cyan',
    name: 'Cyan',
    nameJa: 'シアン',
    hex: '#06B6D4',
    description: '清涼・革新・開放',
    paletteType: 'vivid',
  },
  {
    id: 'sky',
    name: 'Sky',
    nameJa: 'スカイ',
    hex: '#0EA5E9',
    description: '自由・広がり・希望',
    paletteType: 'vivid',
  },
  {
    id: 'blue',
    name: 'Blue',
    nameJa: '青',
    hex: '#3B82F6',
    description: '信頼・安定・知性',
    paletteType: 'vivid',
  },
  {
    id: 'navy',
    name: 'Navy',
    nameJa: 'ネイビー',
    hex: '#1E40AF',
    description: '権威・信頼・専門性',
    paletteType: 'vivid',
  },
  {
    id: 'indigo',
    name: 'Indigo',
    nameJa: 'インディゴ',
    hex: '#6366F1',
    description: '直感・深み・創造',
    paletteType: 'vivid',
  },
  // Purple / Pink
  {
    id: 'violet',
    name: 'Violet',
    nameJa: 'バイオレット',
    hex: '#8B5CF6',
    description: '想像力・精神性・芸術',
    paletteType: 'vivid',
  },
  {
    id: 'purple',
    name: 'Purple',
    nameJa: '紫',
    hex: '#A855F7',
    description: '高級・神秘・創造性',
    paletteType: 'vivid',
  },
  {
    id: 'fuchsia',
    name: 'Fuchsia',
    nameJa: 'フューシャ',
    hex: '#D946EF',
    description: '大胆・遊び心・個性',
    paletteType: 'vivid',
  },
  {
    id: 'magenta',
    name: 'Magenta',
    nameJa: 'マゼンタ',
    hex: '#E879F9',
    description: '革新・芸術・独創性',
    paletteType: 'vivid',
  },
  {
    id: 'pink',
    name: 'Pink',
    nameJa: 'ピンク',
    hex: '#EC4899',
    description: '優しさ・愛情・遊び心',
    paletteType: 'vivid',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    nameJa: 'ラベンダー',
    hex: '#C4B5FD',
    description: '癒し・優雅・穏やか',
    paletteType: 'vivid',
  },
  {
    id: 'peach',
    name: 'Peach',
    nameJa: 'ピーチ',
    hex: '#FDBA74',
    description: '柔らかさ・温もり・親しみ',
    paletteType: 'vivid',
  },
]

// Soft Palette (16 colors)
export const softColours: ColourPreset[] = [
  {
    id: 'soft-pink',
    name: 'Soft Pink',
    nameJa: 'ソフトピンク',
    hex: '#FBD5E0',
    description: '優しさ・可愛らしさ・温もり',
    paletteType: 'soft',
  },
  {
    id: 'blush',
    name: 'Blush',
    nameJa: 'ブラッシュ',
    hex: '#F9A8D4',
    description: '繊細・ロマンチック・柔和',
    paletteType: 'soft',
  },
  {
    id: 'soft-coral',
    name: 'Soft Coral',
    nameJa: 'ソフトコーラル',
    hex: '#FED7AA',
    description: '温かみ・親しみ・安らぎ',
    paletteType: 'soft',
  },
  {
    id: 'apricot',
    name: 'Apricot',
    nameJa: 'アプリコット',
    hex: '#FDCFB4',
    description: '柔らか・温かみ・優しさ',
    paletteType: 'soft',
  },
  {
    id: 'soft-yellow',
    name: 'Soft Yellow',
    nameJa: 'ソフトイエロー',
    hex: '#FEF08A',
    description: '明るさ・軽やかさ・希望',
    paletteType: 'soft',
  },
  {
    id: 'butter',
    name: 'Butter',
    nameJa: 'バター',
    hex: '#FDE68A',
    description: '温かみ・柔らかさ・心地よさ',
    paletteType: 'soft',
  },
  {
    id: 'soft-green',
    name: 'Soft Green',
    nameJa: 'ソフトグリーン',
    hex: '#BBF7D0',
    description: '癒し・自然・穏やか',
    paletteType: 'soft',
  },
  {
    id: 'sage',
    name: 'Sage',
    nameJa: 'セージ',
    hex: '#A7C4BC',
    description: '落ち着き・自然・バランス',
    paletteType: 'soft',
  },
  {
    id: 'soft-mint',
    name: 'Soft Mint',
    nameJa: 'ソフトミント',
    hex: '#A7F3D0',
    description: '爽やか・清涼・リフレッシュ',
    paletteType: 'soft',
  },
  {
    id: 'soft-cyan',
    name: 'Soft Cyan',
    nameJa: 'ソフトシアン',
    hex: '#A5F3FC',
    description: '清らか・開放・透明感',
    paletteType: 'soft',
  },
  {
    id: 'soft-blue',
    name: 'Soft Blue',
    nameJa: 'ソフトブルー',
    hex: '#BFDBFE',
    description: '静けさ・信頼・穏やか',
    paletteType: 'soft',
  },
  {
    id: 'periwinkle',
    name: 'Periwinkle',
    nameJa: 'ペリウィンクル',
    hex: '#C7D2FE',
    description: '静寂・上品・神秘的',
    paletteType: 'soft',
  },
  {
    id: 'soft-lavender',
    name: 'Soft Lavender',
    nameJa: 'ソフトラベンダー',
    hex: '#DDD6FE',
    description: '優雅・癒し・静けさ',
    paletteType: 'soft',
  },
  {
    id: 'lilac',
    name: 'Lilac',
    nameJa: 'ライラック',
    hex: '#E9D5FF',
    description: 'ロマンチック・柔和・夢',
    paletteType: 'soft',
  },
  {
    id: 'soft-gray',
    name: 'Soft Gray',
    nameJa: 'ソフトグレー',
    hex: '#E5E7EB',
    description: 'ニュートラル・落ち着き・上品',
    paletteType: 'soft',
  },
  {
    id: 'ivory',
    name: 'Ivory',
    nameJa: 'アイボリー',
    hex: '#FFFBEB',
    description: '上品・温かみ・クラシック',
    paletteType: 'soft',
  },
]

// Neutral Palette (8 colors)
export const neutralColours: ColourPreset[] = [
  {
    id: 'slate',
    name: 'Slate',
    nameJa: 'スレート',
    hex: '#64748B',
    description: 'プロフェッショナル・落ち着き',
    paletteType: 'neutral',
  },
  {
    id: 'gray',
    name: 'Gray',
    nameJa: 'グレー',
    hex: '#6B7280',
    description: 'ニュートラル・モダン',
    paletteType: 'neutral',
  },
  {
    id: 'zinc',
    name: 'Zinc',
    nameJa: 'ジンク',
    hex: '#71717A',
    description: 'クール・洗練',
    paletteType: 'neutral',
  },
  {
    id: 'stone',
    name: 'Stone',
    nameJa: 'ストーン',
    hex: '#78716C',
    description: '自然・温かみ',
    paletteType: 'neutral',
  },
  {
    id: 'brown',
    name: 'Brown',
    nameJa: 'ブラウン',
    hex: '#A16207',
    description: '安定・信頼・伝統',
    paletteType: 'neutral',
  },
  {
    id: 'sand',
    name: 'Sand',
    nameJa: 'サンド',
    hex: '#D4B896',
    description: '自然・温かみ・ナチュラル',
    paletteType: 'neutral',
  },
  {
    id: 'cream',
    name: 'Cream',
    nameJa: 'クリーム',
    hex: '#FEF3C7',
    description: '柔らかさ・温もり・上品',
    paletteType: 'neutral',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    nameJa: 'チャコール',
    hex: '#374151',
    description: 'モダン・力強さ・洗練',
    paletteType: 'neutral',
  },
]

// All colours combined
export const colourPresets: ColourPreset[] = [...vividColours, ...softColours, ...neutralColours]

// Export by palette type
export const colourPaletteMap = {
  vivid: vividColours,
  soft: softColours,
  neutral: neutralColours,
}
