import type { MovementPreset } from '../../types'

export const movementPresets: MovementPreset[] = [
  {
    id: 'static',
    name: 'Static',
    nameJa: '静的',
    description: '動きを最小限に。落ち着きと安定感を重視',
    keywords: ['安定', '信頼', '堅実', '伝統的'],
    animation: 'none',
  },
  {
    id: 'subtle',
    name: 'Subtle',
    nameJa: 'さりげない',
    description: 'ほぼ気づかない程度の微細な動き',
    keywords: ['上品', '洗練', 'ミニマル', 'プロ'],
    animation: 'subtle',
  },
  {
    id: 'smooth',
    name: 'Smooth',
    nameJa: 'なめらか',
    description: 'ゆっくりとした滑らかなトランジション',
    keywords: ['優雅', '心地よい', 'リラックス', '穏やか'],
    animation: 'smooth',
  },
  {
    id: 'gentle',
    name: 'Gentle',
    nameJa: 'やさしい',
    description: '柔らかく優しい印象の動き',
    keywords: ['親しみ', '温かみ', 'フレンドリー', '安心'],
    animation: 'gentle',
  },
  {
    id: 'responsive',
    name: 'Responsive',
    nameJa: 'レスポンシブ',
    description: 'ユーザー操作に素早く反応する動き',
    keywords: ['直感的', 'モダン', '効率的', 'スマート'],
    animation: 'responsive',
  },
  {
    id: 'dynamic',
    name: 'Dynamic',
    nameJa: 'ダイナミック',
    description: '活気のある印象的な動き',
    keywords: ['エネルギッシュ', '活発', '若々しい', 'アクティブ'],
    animation: 'dynamic',
  },
  {
    id: 'playful',
    name: 'Playful',
    nameJa: '遊び心',
    description: 'バウンスやイージングで楽しさを演出',
    keywords: ['楽しい', 'カジュアル', 'ポップ', 'クリエイティブ'],
    animation: 'playful',
  },
  {
    id: 'energetic',
    name: 'Energetic',
    nameJa: 'エネルギッシュ',
    description: '力強く印象に残る大胆な動き',
    keywords: ['大胆', 'インパクト', '革新的', '刺激的'],
    animation: 'energetic',
  },
]
