import type { ShapePreset } from '../../types'

export const shapePresets: ShapePreset[] = [
  {
    id: 'geometric',
    name: 'Geometric',
    nameJa: 'ジオメトリック',
    description: '直線と角度を活かしたシャープなデザイン',
    keywords: ['モダン', 'クリーン', '論理的', 'プロフェッショナル'],
    shapeType: 'geometric',
  },
  {
    id: 'rounded',
    name: 'Rounded',
    nameJa: 'ラウンド',
    description: '角を丸めた親しみやすいデザイン',
    keywords: ['フレンドリー', '親しみ', 'やさしい', 'カジュアル'],
    shapeType: 'rounded',
  },
  {
    id: 'circular',
    name: 'Circular',
    nameJa: 'サーキュラー',
    description: '円や楕円を基調とした柔らかなデザイン',
    keywords: ['調和', '完全', '柔軟', 'コミュニティ'],
    shapeType: 'circular',
  },
  {
    id: 'organic',
    name: 'Organic',
    nameJa: 'オーガニック',
    description: '自然界の形を取り入れた有機的なデザイン',
    keywords: ['自然', '流動的', 'アート', 'クリエイティブ'],
    shapeType: 'organic',
  },
  {
    id: 'angular',
    name: 'Angular',
    nameJa: 'アンギュラー',
    description: '鋭角を活かしたダイナミックなデザイン',
    keywords: ['大胆', 'エッジー', '革新的', 'インパクト'],
    shapeType: 'angular',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    nameJa: 'ミニマル',
    description: 'シンプルな形で余白を活かすデザイン',
    keywords: ['シンプル', '洗練', '上品', 'エレガント'],
    shapeType: 'minimal',
  },
  {
    id: 'striped',
    name: 'Striped',
    nameJa: 'ストライプ',
    description: '縞模様でリズムと動きを表現するデザイン',
    keywords: ['リズム', '動き', 'シャープ', 'スタイリッシュ'],
    shapeType: 'striped',
  },
  {
    id: 'grid',
    name: 'Grid',
    nameJa: 'グリッド',
    description: '格子状の構造で秩序を表現するデザイン',
    keywords: ['秩序', '構造', 'システマティック', '整然'],
    shapeType: 'grid',
  },
  {
    id: 'dots',
    name: 'Dots',
    nameJa: 'ドット',
    description: '水玉模様で遊び心を表現するデザイン',
    keywords: ['ポップ', '遊び心', 'レトロ', 'キュート'],
    shapeType: 'dots',
  },
  {
    id: 'hexagon',
    name: 'Hexagon',
    nameJa: 'ヘキサゴン',
    description: '六角形で先進的な印象を与えるデザイン',
    keywords: ['テック', '先進的', '効率', 'サイエンス'],
    shapeType: 'hexagon',
  },
  {
    id: 'diamond',
    name: 'Diamond',
    nameJa: 'ダイヤモンド',
    description: 'ひし形で高級感を演出するデザイン',
    keywords: ['高級', 'スタイリッシュ', '洗練', 'プレミアム'],
    shapeType: 'diamond',
  },
  {
    id: 'pattern',
    name: 'Pattern',
    nameJa: 'パターン',
    description: '繰り返しモチーフで個性を出すデザイン',
    keywords: ['デコラティブ', '個性的', '印象的', 'アーティスティック'],
    shapeType: 'pattern',
  },
  {
    id: 'wave',
    name: 'Wave',
    nameJa: 'ウェーブ',
    description: '波形で流れや柔軟さを表現するデザイン',
    keywords: ['流れ', '柔軟', 'リラックス', 'SaaS'],
    shapeType: 'wave',
  },
  {
    id: 'pill',
    name: 'Pill',
    nameJa: 'ピル',
    description: 'カプセル型でモバイルフレンドリーなデザイン',
    keywords: ['モバイル', 'タグ', 'ボタン', 'コンパクト'],
    shapeType: 'pill',
  },
  {
    id: 'blob',
    name: 'Blob',
    nameJa: 'ブロブ',
    description: '不定形で遊び心のあるトレンドデザイン',
    keywords: ['遊び心', '柔らか', 'トレンド', 'ユニーク'],
    shapeType: 'blob',
  },
]
