import type { ShapePreset } from '../../types'

export const shapePresets: ShapePreset[] = [
  {
    id: 'sharp',
    label: 'Sharp',
    labelJa: 'シャープ',
    description: 'Angular, straight lines',
    descriptionJa: '角張った、直線的',
    cssValue: { borderRadius: 'none' },
  },
  {
    id: 'subtle',
    label: 'Subtle',
    labelJa: 'サトル',
    description: 'Slightly rounded corners',
    descriptionJa: 'わずかに丸みを帯びた',
    cssValue: { borderRadius: 'sm' },
  },
  {
    id: 'rounded',
    label: 'Rounded',
    labelJa: 'ラウンド',
    description: 'Moderately rounded',
    descriptionJa: '程よい丸み',
    cssValue: { borderRadius: 'md' },
  },
  {
    id: 'soft',
    label: 'Soft',
    labelJa: 'ソフト',
    description: 'Soft, gentle curves',
    descriptionJa: '柔らかい丸み',
    cssValue: { borderRadius: 'lg' },
  },
  {
    id: 'pill',
    label: 'Pill',
    labelJa: 'ピル',
    description: 'Fully rounded (capsule)',
    descriptionJa: '完全に丸い（カプセル型）',
    cssValue: { borderRadius: 'full' },
  },
  {
    id: 'geometric',
    label: 'Geometric',
    labelJa: 'ジオメトリック',
    description: 'Geometric, regular shapes',
    descriptionJa: '幾何学的、規則正しい',
    cssValue: { borderRadius: 'none' },
  },
  {
    id: 'organic',
    label: 'Organic',
    labelJa: 'オーガニック',
    description: 'Organic, natural curves',
    descriptionJa: '有機的、自然な曲線',
    cssValue: { borderRadius: 'lg' },
  },
  {
    id: 'minimal',
    label: 'Minimal',
    labelJa: 'ミニマル',
    description: 'Minimal decoration',
    descriptionJa: '最小限の装飾',
    cssValue: { borderRadius: 'sm' },
  },
  {
    id: 'bold',
    label: 'Bold',
    labelJa: 'ボールド',
    description: 'Bold, impactful presence',
    descriptionJa: '大胆、存在感のある',
    cssValue: { borderRadius: 'md' },
  },
  {
    id: 'playful',
    label: 'Playful',
    labelJa: 'プレイフル',
    description: 'Playful, fun shapes',
    descriptionJa: '遊び心のある形',
    cssValue: { borderRadius: 'full' },
  },
]
